### ISSUE TITLE
Error on Terraform v0.12

### ISSUE THREAD

**Issue by chrisduong** [terraform-aws-modules/terraform-aws-security-group#117]
Hi,

I faced this error with Terraform v0.12.

> Error: Incorrect attribute value type
> 
>   on .terraform/modules/web_alb_sg/terraform-aws-modules-terraform-aws-security-group-9969c25/main.tf line 151, in resource "aws_security_group_rule" "ingress_with_ipv6_cidr_blocks":
>  151:   ipv6_cidr_blocks = ["${split(",", lookup(var.ingress_with_ipv6_cidr_blocks[count.index], "ipv6_cidr_blocks", join(",", var.ingress_ipv6_cidr_blocks)))}"]
> 
> Inappropriate value for attribute "ipv6_cidr_blocks": element 0: string
> required.

**Comment by ssanbeg** [comment]
Also using Terraform 0.12.0 and source  = "terraform-aws-modules/security-group/aws"
  version = "2.17.0"

in resource "aws_security_group_rule" "computed_ingress_with_cidr_blocks":
 135:   cidr_blocks     = ["${split(",", lookup(var.computed_ingress_with_cidr_blocks[count.index], "cidr_blocks", join(",", var.ingress_cidr_blocks)))}"]

Inappropriate value for attribute "cidr_blocks": element 0: string required.

**Comment by antonbabenko** [comment]
Stay tuned, this module is not compatible with Terraform 0.12 yet. Work is in progress.

**Comment by antonbabenko** [comment]
[v3.0.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v3.0.0) has been just released. 🎉 

Please give it a try and report any issues you discover.

**Comment by boisde** [comment]
the v3.4.0 has got the same issue.

**Comment by kuritonasu** [comment]
See #105. @antonbabenko points out that it is (or at least was) a Terraform limitation. cidr_blocks expects a **comma separated string** with the cidr blocks, instead of an actual list. I am not sure if this is still intended behaviour as the last two comments imply that it's not. 

In order to overcome this, instead of using 
`cidr_blocks = var.allowed_cidrs`
use
`cidr_blocks = join(",",var.allowed_cidrs)`
