### ISSUE TITLE
terraform 0.11.13 -  At 5:16: Unknown token: 5:16 IDENT concat

### ISSUE THREAD

**Issue by pawarrchetan** [terraform-aws-modules/terraform-aws-security-group#124]
Getting error   "At 5:16: Unknown token: 5:16 IDENT concat" when using the version of this module with terraform 0.11.13.

**Comment by pawarrchetan** [comment]
# tf version
Terraform v0.11.13

Your version of Terraform is out of date! The latest version
is 0.12.0. You can update by downloading from www.terraform.io/downloads.html

module "sonarqube_rds_security_group" {
  source              = "github.com/terraform-aws-modules/terraform-aws-security-group"
  version             = "~> 2.0"
  name                = "sonarqube-rds-security-group"
  description         = "Security group for sonarqube RDS Instance with postgres ports open within VPC"
  vpc_id              = "vpc-0ee41768e7aa8f9fb"
  ingress_cidr_blocks = ["10.1.12.0/24", "10.1.0.0/24", "10.1.1.0/24", "10.1.3.0/24", "10.1.7.0/24"]
  ingress_rules       = ["postgresql-tcp"]
}

- module.sonarqube_rds_security_group
  Getting source "github.com/terraform-aws-modules/terraform-aws-security-group"
Error downloading modules: Error loading modules: module sonarqube_rds_security_group: Error parsing .terraform/modules/debe0a30108fd090f9d56347496e466d/main.tf: At 5:16: Unknown token: 5:16 IDENT concat

The error still persists when we use specific version such as "2.16.0" or "2.17.0" compatible with terraform 0.11.13.

**Comment by fabiendelpierre** [comment]
Your syntax is incorrect. You cannot use the `version` parameter when you are not using the Terraform Module Registry. The way you have it in your code, the parser is ignoring the `version` parameter entirely, and since you effectively did not specify a version to download, it's grabbing the latest code that is compatible only with Terraform 0.12.

So you can do one of two things: when possible and if desired, use the Registry, and this will work:
```
module "sonarqube" {
  source = "terraform-aws-modules/security-group/aws"
  version = "~> 2.0"
  ...
}
```
Or if you want to fetch directly from GitHub:
```
module "sonarqube" {
  source = "github.com/terraform-aws-modules/terraform-aws-security-group?ref=v2.17.0"
  ...
}
```

Obviously this doesn't support versioning constraints since it's a simple Git ref. Note that you need the "v" because the tags for this module include it (see [list](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases)).

Further details [here](https://www.terraform.io/docs/modules/sources.html).

**Comment by pawarrchetan** [comment]
@fabiendelpierre 

Awesome. That worked.
I figured out that the repository was not correct.
But thanks to you I have 2 ways of doing it now.

Regards...
Chetan
