### ISSUE TITLE
Add option to create the same security group in multiple VPCs

### ISSUE THREAD

**Issue by gek0** [terraform-aws-modules/terraform-aws-security-group#136]
Would it be possible to add an option what this module has the VPC ID as type list instead of string?
My use case: I would like to manage custom "default" security group for all accounts - meaning I need to create the same group in multiple VPCs.
Since module resources still does not support `count` and `for_each` this sounds like an only options. I could go with creating a custom module for this, but that sounds like re-inventing the wheel when a complete module like this already exists.

Thanks!

**Comment by bryantbiggs** [comment]
hi @gek0 I think this is more of a module composition problem rather than module feature. its not common enough where mapping VPCs would be beneficial, instead I would look at how your are deploying VPCs and if that can accommodate this change for you. for example, with a landing zone type implementation then perhaps you bake in the creation of these "default" VPCs
