### ISSUE TITLE
Add security group ARN attribute to the module output

### ISSUE THREAD

**Issue by harloprillar** [terraform-aws-modules/terraform-aws-security-group#247]
ARN attribute of the security group created by this module not available, whereas it exists in official AWS provider 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#arn

**Comment by dhoppe** [comment]
The additional output `arn` is available since version 3.29.0 of the Terraform AWS provider. 
https://github.com/hashicorp/terraform-provider-aws/pull/13944#issuecomment-782201689

This means the version constraint needs to be modified and since this is an backwards incompatible change, a new release is necessary. 

All the examples need to be modified as well.
https://github.com/terraform-aws-modules/terraform-aws-security-group/pull/230/

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.10.0 :tada:
