### ISSUE TITLE
make lifecycle create_before_destroy configurable 

### ISSUE THREAD

**Issue by tchia04** [terraform-aws-modules/terraform-aws-security-group#40]
Current default behavior is to destroy the resource before creating a new one.

Can we make lifecycle create_before_destroy default to true or make it configurable by the caller to avoid any potential down time? 

I tried this tf and it didn't work

<pre>
module "web_server_sg" {
  source = "terraform-aws-modules/security-group/aws//modules/http-80"

  name        = "web-server"
  description = "Security group for web-server with HTTP ports open within VPC. Managed by Terraform"
  vpc_id      = "${data.aws_vpc.default.id}"

  ingress_cidr_blocks   = ["0.0.0.0/0"]

  lifecycle {
    create_before_destroy = true
  }
}
</pre>
The error message is 
terraform plan

Error: module "web_server_sg": "lifecycle" is not a valid argument

I would like to use it like this if it's possible similar to create=true
<pre>
module "web_server_sg" {
  source = "terraform-aws-modules/security-group/aws//modules/http-80"

  name        = "web-server"
  description = "Security group for web-server with HTTP ports open within VPC. Managed by Terraform"
  vpc_id      = "${data.aws_vpc.default.id}"

  ingress_cidr_blocks = ["0.0.0.0/0"]

  create_before_destroy = true

}
</pre>

**Comment by antonbabenko** [comment]
An important note is that lifecycle `create_before_destroy` specified in the module is not going to have an effect on resources created outside of this module but only inside of the same module. This means that simply adding `create_before_destroy = true` into the module won't help with your case.

**Comment by ndench** [comment]
@antonbabenko by not having `create_before_destroy = true` making changes to the security group is prevented. The rules can be updated, but changing something on the group itself that requires a new resource is blocked (eg. name, description).

It gets blocked because the security group is in use, so terraform cannot destroy it before creating the new one. If we specify `create_before_destroy = true` then the new group will be created, everything using the old group will be switched over, then the old group can be successfully destroyed.

I think it would definitely be valuable to have this and I'm happy to do a PR if you like?

**Comment by antonbabenko** [comment]
@ndench Thanks for bringing this issue back.

I have just fixed it and released [v2.3.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v2.3.0)

**Comment by ndench** [comment]
No worries @antonbabenko, thanks for the speedy fix!

**Comment by antonbabenko** [comment]
@alrosot You are right, thanks for raising this issue. I have just made a new release [v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v2.4.0) which fixes this issue. And, hopefully, does not bring new issues. Please confirm that it works as expected.

**Comment by alrosot** [comment]
That was really cool @antonbabenko! I was just whining and actually got a super fast fix!
I can confirm the issue is gone in version 2.4.0. Thank you!

**Comment by antonbabenko** [comment]
Great that it works for you. You should always pin the version of Terraform modules you are using from external sources (like this one) to prevent such surprises in the future. :)

**Comment by robinbowes** [comment]
I've just started using the module, and this latest change is a possible blocker for us. We're using the SG Name as the contract between terraform and our other orchestration. ie. our orchestration that creates service instances, expects a SG to exist with the name `<service>-<stage>-<site>` (eg. `web-development-us01`). Since this latest change, that is no longer the case since the group is named, eg. `web-development-us01-20180910233446932900000001`.

Not sure what I think yet as it's latest and I've just hit this. 

I'll think some more tomorrow...

**Comment by robinbowes** [comment]
I've created a new issue: #73

**Comment by robinbowes** [comment]
Hi Anton,

Thanks for the reply.

We're currently using the name of the security group as the contract between two separate tools, so we need it to stay the same (which it will, once created, as it's immutable).

(I've just seen you've replied to #73 so I'll go and follow up there)

R.
