### ISSUE TITLE
Unable to create a security group with a specific name

### ISSUE THREAD

**Issue by robinbowes** [terraform-aws-modules/terraform-aws-security-group#73]
Since v2.4.0, it is not possible to create a security group with a specific name. This is because https://github.com/terraform-aws-modules/terraform-aws-security-group/commit/5e998c5c1a51c1c203f8c5a85ddf1c1aaad4793d changed from using the `name` parameter to using the `name_prefix` parameter.

I'm working around it by using a fork with the latest change reverted but I think not being able to create a group with a specific name is a pretty fatal flaw in the module.

Additionally, this is a breaking change since it will cause all security groups managed by this module to be renamed.

Can you possibly reconsider?

**Comment by antonbabenko** [comment]
I agree, that it _may_ be a good idea to create security group by specifying `name` or `name_prefix`. Terraform 0.12 should make this possible since there will be a support for dynamic arguments.

Please consider the following and tell me if this works for you:

---

I thought about this as well before making the change you are referring to.

The solution which I recommend and use myself is to use `terraform output this_security_group_id` to get a complete security group when necessary.

If you don't want to use `terraform output` you can call `aws s3 cp .. - | jq ...` to get a value from the state file directly. This is a bit ugly, but will work.

**Comment by robinbowes** [comment]
Hi.

Looks like I'll continue using my fork until 0.12 drops.

Thanks,

R.

**Comment by antonbabenko** [comment]
Ok, but actually, it is possible to add this feature to this module right now but the module will become a bit harder to maintain.

**Comment by robinbowes** [comment]
Really? I've not been able to figure out how to optionally specify `name` or `name_prefix`. How would you do that?

**Comment by antonbabenko** [comment]
1. Make two security groups - one with `name`, another with `name_prefix`
1. Use `locals` to find the first, which is not empty, and store it as `local.security_group_id`
1. Update references to use `local.security_group_id`

Check [terraform-aws-rds module](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L20) for details. It has similar idea implemented.

PR is welcome :)

**Comment by robinbowes** [comment]
> PR is welcome :)

Challenge accepted. :)
