### ISSUE TITLE
How could one adopt the Default Security Group with this module.

### ISSUE THREAD

**Issue by iveskins** [terraform-aws-modules/terraform-aws-security-group#87]
The terraform documentation here https://www.terraform.io/docs/providers/aws/r/default_security_group.html describes 
adopting the Default Security Group to make it be managed by terraform.

Is there a way to do this with this module also?

Thanks.

**Comment by antonbabenko** [comment]
Right now there is no way to manage the Default Security Group using this module.

I don't think we will make it possible in the nearest future, because it is an advanced resource with its own special tricks and this module implements creation of new security group and rules but not extending existing security groups created outside of the module.
